engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
  eslint:
    enabled: true
    config:
      config: tests/.eslint.yml
  scss-lint:
    enabled: true
    config:
      config: tests/.scsslint.yml

ratings:
  paths:
    - app/**/*.php
    - resources/assets/**/*.js
    - resources/assets/**/*.scss

exclude_paths:
  - node_modules/*
  - public/*
  - tests/*
  - vendor/*
