engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true

ratings:
  paths:
    - app/api/**.php

exclude_paths:
  - res/*
  - tests/*
  - public/*
  - vendor/*
