language: php

sudo: false

env:
 - $NODEJS_VERSION=6

matrix:
  fast_finish: true

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - bash -c "nvm use $NODEJS_VERSION" || true
  - bash -c "source ~/.nvm/nvm.sh; nvm install $NODEJS_VERSION; node --version"

install:
  - npm -g update && npm i -q
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:dev-master squizlabs/php_codesniffer:^2.6 -n -q; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n -q; fi

script:
  - gulp build
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then php vendor/bin/phpunit -c tests/phpunit.xml --coverage-text; fi
  - if [[  "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover tests/clover.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/phpcs --standard=PSR2 --ignore=src/routes/*,src/bootstrap.php,src/settings.php -n -p src/; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls -v; fi
