CREATE TABLE IF NOT EXISTS dummy (
  id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  deleted_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT NULL
);
CREATE UNIQUE INDEX dummy_name_uindex ON dummy (name);
