language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:dev-master -n -q; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n -q; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then php vendor/bin/phpunit -c tests/phpunit.xml --coverage-text; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover tests/clover.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer lint; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls -v; fi
